# Generated by Django 3.2 on 2021-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Genre Name'),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Artist Name')),
                ('description', models.CharField(max_length=100, verbose_name='Artist Description')),
                ('age', models.IntegerField(verbose_name='Artist Age')),
                ('genres', models.ManyToManyField(to='music.Genre', verbose_name='Artist Genres')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
    ]
