# Generated by Django 3.2 on 2021-04-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_artist_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Album Name')),
                ('description', models.CharField(max_length=100, verbose_name='Album Description')),
                ('artists', models.ManyToManyField(to='music.Artist', verbose_name='Album Owners')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
