# Generated by Django 3.2 on 2021-04-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Genre Name'),
        ),
    ]
